# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choosing_game_feature_main_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChoosingGameFeature(object):
    def setupUi(self, ChoosingGameFeature):
        ChoosingGameFeature.setObjectName("ChoosingGameFeature")
        ChoosingGameFeature.resize(325, 415)
        self.button_box = QtWidgets.QDialogButtonBox(ChoosingGameFeature)
        self.button_box.setGeometry(QtCore.QRect(160, 390, 156, 23))
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayoutWidget = QtWidgets.QWidget(ChoosingGameFeature)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 230, 321, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.game_types_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.game_types_layout.setContentsMargins(10, 0, 10, 0)
        self.game_types_layout.setObjectName("game_types_layout")
        self.game_type_lb = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.game_type_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.game_type_lb.setObjectName("game_type_lb")
        self.game_types_layout.addWidget(self.game_type_lb)
        self.game_types_scroll = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        self.game_types_scroll.setWidgetResizable(True)
        self.game_types_scroll.setObjectName("game_types_scroll")
        self.scroll_area_widget_contents_2 = QtWidgets.QWidget()
        self.scroll_area_widget_contents_2.setGeometry(QtCore.QRect(0, 0, 299, 128))
        self.scroll_area_widget_contents_2.setObjectName("scroll_area_widget_contents_2")
        self.game_types_scroll.setWidget(self.scroll_area_widget_contents_2)
        self.game_types_layout.addWidget(self.game_types_scroll)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(ChoosingGameFeature)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 321, 231))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.player_names_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.player_names_layout.setContentsMargins(10, 0, 10, 0)
        self.player_names_layout.setObjectName("player_names_layout")
        self.player_names_lb = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.player_names_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.player_names_lb.setObjectName("player_names_lb")
        self.player_names_layout.addWidget(self.player_names_lb)
        self.random_players_query_checkbox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.random_players_query_checkbox.setObjectName("random_players_query_checkbox")
        self.player_names_layout.addWidget(self.random_players_query_checkbox)
        self.player_names_scroll = QtWidgets.QScrollArea(self.verticalLayoutWidget_2)
        self.player_names_scroll.setWidgetResizable(True)
        self.player_names_scroll.setObjectName("player_names_scroll")
        self.scroll_area_widget_contents = QtWidgets.QWidget()
        self.scroll_area_widget_contents.setGeometry(QtCore.QRect(0, 0, 299, 185))
        self.scroll_area_widget_contents.setObjectName("scroll_area_widget_contents")
        self.player_names_scroll.setWidget(self.scroll_area_widget_contents)
        self.player_names_layout.addWidget(self.player_names_scroll)
        self.error_lb = QtWidgets.QLabel(ChoosingGameFeature)
        self.error_lb.setGeometry(QtCore.QRect(10, 390, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.error_lb.setFont(font)
        self.error_lb.setText("")
        self.error_lb.setObjectName("error_lb")

        self.retranslateUi(ChoosingGameFeature)
        QtCore.QMetaObject.connectSlotsByName(ChoosingGameFeature)

    def retranslateUi(self, ChoosingGameFeature):
        _translate = QtCore.QCoreApplication.translate
        ChoosingGameFeature.setWindowTitle(_translate("ChoosingGameFeature", "Form"))
        self.game_type_lb.setText(_translate("ChoosingGameFeature", "Режим игры"))
        self.player_names_lb.setText(_translate("ChoosingGameFeature", "Имена игроков"))
        self.random_players_query_checkbox.setText(_translate("ChoosingGameFeature", "Случайный порядок игроков"))
