# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choosing_filter_main_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChoosingFilterMainMenu(object):
    def setupUi(self, ChoosingFilterMainMenu):
        ChoosingFilterMainMenu.setObjectName("ChoosingFilterMainMenu")
        ChoosingFilterMainMenu.resize(325, 415)
        self.formLayoutWidget = QtWidgets.QWidget(ChoosingFilterMainMenu)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 321, 61))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.form_layout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.form_layout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.form_layout.setContentsMargins(50, 0, 50, 0)
        self.form_layout.setObjectName("form_layout")
        self.num_players_lb = QtWidgets.QLabel(self.formLayoutWidget)
        self.num_players_lb.setObjectName("num_players_lb")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.num_players_lb)
        self.num_players_combo = QtWidgets.QComboBox(self.formLayoutWidget)
        self.num_players_combo.setObjectName("num_players_combo")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.num_players_combo)
        self.game_type_lb = QtWidgets.QLabel(self.formLayoutWidget)
        self.game_type_lb.setObjectName("game_type_lb")
        self.form_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.game_type_lb)
        self.game_type_combo = QtWidgets.QComboBox(self.formLayoutWidget)
        self.game_type_combo.setObjectName("game_type_combo")
        self.form_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.game_type_combo)
        self.button_box = QtWidgets.QDialogButtonBox(ChoosingFilterMainMenu)
        self.button_box.setGeometry(QtCore.QRect(160, 390, 161, 23))
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.savings_list = QtWidgets.QListWidget(ChoosingFilterMainMenu)
        self.savings_list.setGeometry(QtCore.QRect(0, 60, 321, 311))
        self.savings_list.setObjectName("savings_list")
        self.error_lb = QtWidgets.QLabel(ChoosingFilterMainMenu)
        self.error_lb.setGeometry(QtCore.QRect(10, 390, 141, 16))
        self.error_lb.setText("")
        self.error_lb.setObjectName("error_lb")
        self.additional_btn = QtWidgets.QPushButton(ChoosingFilterMainMenu)
        self.additional_btn.setGeometry(QtCore.QRect(246, 370, 76, 21))
        self.additional_btn.setObjectName("additional_btn")

        self.retranslateUi(ChoosingFilterMainMenu)
        QtCore.QMetaObject.connectSlotsByName(ChoosingFilterMainMenu)

    def retranslateUi(self, ChoosingFilterMainMenu):
        _translate = QtCore.QCoreApplication.translate
        ChoosingFilterMainMenu.setWindowTitle(_translate("ChoosingFilterMainMenu", "MainMenu"))
        self.num_players_lb.setText(_translate("ChoosingFilterMainMenu", "Количество игроков"))
        self.game_type_lb.setText(_translate("ChoosingFilterMainMenu", "Режим игры"))
        self.additional_btn.setText(_translate("ChoosingFilterMainMenu", "Случайная"))
