# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomeMainMenu(object):
    def setupUi(self, HomeMainMenu):
        HomeMainMenu.setObjectName("HomeMainMenu")
        HomeMainMenu.resize(325, 415)
        self.verticalLayoutWidget = QtWidgets.QWidget(HomeMainMenu)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 321, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.main_menu_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.main_menu_layout.setContentsMargins(100, 100, 100, 100)
        self.main_menu_layout.setObjectName("main_menu_layout")
        self.play_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.play_btn.setObjectName("play_btn")
        self.main_menu_layout.addWidget(self.play_btn)
        self.statistics_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.statistics_btn.setObjectName("statistics_btn")
        self.main_menu_layout.addWidget(self.statistics_btn)
        self.level_editor_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.level_editor_btn.setObjectName("level_editor_btn")
        self.main_menu_layout.addWidget(self.level_editor_btn)

        self.retranslateUi(HomeMainMenu)
        QtCore.QMetaObject.connectSlotsByName(HomeMainMenu)

    def retranslateUi(self, HomeMainMenu):
        _translate = QtCore.QCoreApplication.translate
        HomeMainMenu.setWindowTitle(_translate("HomeMainMenu", "MainMenu"))
        self.play_btn.setText(_translate("HomeMainMenu", "Играть"))
        self.statistics_btn.setText(_translate("HomeMainMenu", "Статистики"))
        self.level_editor_btn.setText(_translate("HomeMainMenu", "Редактор уровней"))
