# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'level_editor_main_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LevelEditorMainMenu(object):
    def setupUi(self, LevelEditorMainMenu):
        LevelEditorMainMenu.setObjectName("LevelEditorMainMenu")
        LevelEditorMainMenu.resize(325, 415)
        self.label = QtWidgets.QLabel(LevelEditorMainMenu)
        self.label.setGeometry(QtCore.QRect(10, 10, 311, 16))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.button_box = QtWidgets.QDialogButtonBox(LevelEditorMainMenu)
        self.button_box.setGeometry(QtCore.QRect(210, 390, 111, 23))
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.formLayoutWidget_2 = QtWidgets.QWidget(LevelEditorMainMenu)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 286, 321, 104))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.form_layout = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.form_layout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.form_layout.setContentsMargins(10, 0, 10, 0)
        self.form_layout.setObjectName("form_layout")
        self.map_name_edit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.map_name_edit.setObjectName("map_name_edit")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.map_name_edit)
        self.size_field_lb = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.size_field_lb.setObjectName("size_field_lb")
        self.form_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.size_field_lb)
        self.size_layout = QtWidgets.QHBoxLayout()
        self.size_layout.setObjectName("size_layout")
        self.spin_size_lengh = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.spin_size_lengh.setMinimum(1)
        self.spin_size_lengh.setObjectName("spin_size_lengh")
        self.size_layout.addWidget(self.spin_size_lengh)
        self.spin_size_width = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.spin_size_width.setMinimum(1)
        self.spin_size_width.setObjectName("spin_size_width")
        self.size_layout.addWidget(self.spin_size_width)
        self.form_layout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.size_layout)
        self.available_game_types_lb = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.available_game_types_lb.setObjectName("available_game_types_lb")
        self.form_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.available_game_types_lb)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.game_type_classic_checkbox = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.game_type_classic_checkbox.setObjectName("game_type_classic_checkbox")
        self.gridLayout.addWidget(self.game_type_classic_checkbox, 0, 0, 1, 1)
        self.game_type_blindness_checkbox = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.game_type_blindness_checkbox.setObjectName("game_type_blindness_checkbox")
        self.gridLayout.addWidget(self.game_type_blindness_checkbox, 0, 1, 1, 1)
        self.form_layout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.gridLayout)
        self.make_new_map_btn = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.make_new_map_btn.setObjectName("make_new_map_btn")
        self.form_layout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.make_new_map_btn)
        self.map_name_lb = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.map_name_lb.setObjectName("map_name_lb")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.map_name_lb)
        self.savings_list = QtWidgets.QListWidget(LevelEditorMainMenu)
        self.savings_list.setGeometry(QtCore.QRect(0, 30, 321, 251))
        self.savings_list.setObjectName("savings_list")
        self.error_lb = QtWidgets.QLabel(LevelEditorMainMenu)
        self.error_lb.setGeometry(QtCore.QRect(0, 393, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.error_lb.setFont(font)
        self.error_lb.setText("")
        self.error_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.error_lb.setObjectName("error_lb")
        self.delet_btn = QtWidgets.QPushButton(LevelEditorMainMenu)
        self.delet_btn.setGeometry(QtCore.QRect(150, 390, 51, 23))
        self.delet_btn.setObjectName("delet_btn")

        self.retranslateUi(LevelEditorMainMenu)
        QtCore.QMetaObject.connectSlotsByName(LevelEditorMainMenu)

    def retranslateUi(self, LevelEditorMainMenu):
        _translate = QtCore.QCoreApplication.translate
        LevelEditorMainMenu.setWindowTitle(_translate("LevelEditorMainMenu", "MainMenu"))
        self.label.setText(_translate("LevelEditorMainMenu", "Выберите карту для редактирования"))
        self.size_field_lb.setText(_translate("LevelEditorMainMenu", "Размеры поля (длина/ширина)"))
        self.available_game_types_lb.setText(_translate("LevelEditorMainMenu", "Доступные режимы игры"))
        self.game_type_classic_checkbox.setText(_translate("LevelEditorMainMenu", "Classic"))
        self.game_type_blindness_checkbox.setText(_translate("LevelEditorMainMenu", "Blindness"))
        self.make_new_map_btn.setText(_translate("LevelEditorMainMenu", "Создать новую карту"))
        self.map_name_lb.setText(_translate("LevelEditorMainMenu", "Название карты"))
        self.delet_btn.setText(_translate("LevelEditorMainMenu", "Delete"))
